# @todo: legacy links can be uncommented when page is fully migrated.
admin_features_index:
  path: /
  methods: [ GET ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\Catalog\FeatureController::indexAction
    _legacy_controller: AdminFeatures
    _legacy_link: AdminFeatures
    _legacy_feature_flag: feature

admin_features_horizontal_index:
  path: /horizontal
  methods: [ GET, POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\Catalog\HorizontalFeatureController::indexAction
    _legacy_controller: AdminFeatures

admin_features_search:
  path: /
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\CommonController::searchGridAction
    _legacy_controller: AdminFeatures
    # _legacy_link: AdminFeatures
    gridDefinitionFactoryServiceId: PrestaShop\PrestaShop\Core\Grid\Definition\Factory\FeatureGridDefinitionFactory
    redirectRoute: admin_features_index

admin_features_add:
  path: /new
  methods: [ GET, POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\Catalog\FeatureController::createAction
    _legacy_controller: AdminFeatures
    _legacy_link: AdminFeatures:addfeature
    _legacy_feature_flag: feature

admin_features_edit:
  path: /{featureId}/edit
  methods: [ GET, POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\Catalog\FeatureController::editAction
    _legacy_controller: AdminFeatures
    _legacy_link: AdminFeatures:updatefeature
    _legacy_feature_flag: feature
    _legacy_parameters:
      id_feature: featureId
  requirements:
    featureId: \d+

admin_features_export:
  path: /export
  methods: GET
  defaults:
    _controller: 'PrestaShopBundle\Controller\Admin\Sell\Catalog\FeatureController::exportAction'
    _legacy_controller: AdminFeatures

admin_features_update_position:
  path: /update-position
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\CommonController::updatePositionAction
    _legacy_controller: AdminFeatures
    position_definition: prestashop.core.grid.feature.position_definition
    redirect_route: admin_features_index

admin_features_delete:
  path: /{featureId}/delete
  methods: [ POST, DELETE ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\Catalog\FeatureController::deleteAction
    _legacy_controller: AdminFeatures
  requirements:
    featureId: \d+

admin_features_bulk_delete:
  path: /bulk-delete
  methods: [ POST, DELETE ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\Catalog\FeatureController::bulkDeleteAction
    _legacy_controller: AdminFeatures
  requirements:
    featureId: \d+
